#!/bin/bash

echo "Instructions to restart local Lumen services"
echo "============================================="
echo ""
echo "Since you're running Lumen services locally, you need to restart them:"
echo ""
echo "1. Stop current services (if running via php artisan serve):"
echo "   - Press Ctrl+C in each terminal"
echo ""
echo "2. Restart ticket-service:"
echo "   cd /root/AidlY/services/ticket-service"
echo "   php artisan serve --host=0.0.0.0 --port=8002"
echo ""
echo "3. Restart email-service:"
echo "   cd /root/AidlY/services/email-service"
echo "   php artisan serve --host=0.0.0.0 --port=8005"
echo ""
echo "Or if using screen/tmux, restart the sessions."
echo ""
echo "The code changes we made will only take effect after restart!"
