_format_version: "3.0"
_transform: true

services:
  # Authentication Service - Public endpoints
  - name: auth-service
    url: http://auth-service:8001
    connect_timeout: 10000
    write_timeout: 10000
    read_timeout: 10000
    retries: 3
    routes:
      - name: auth-public-routes
        paths:
          - /api/v1/auth/login
          - /api/v1/auth/register
          - /api/v1/auth/forgot-password
          - /api/v1/auth/reset-password
          - /api/v1/auth/verify-email
        methods:
          - GET
          - POST
        strip_path: false
        preserve_host: true
      - name: auth-protected-routes
        paths:
          - /api/v1/auth/user
          - /api/v1/auth/refresh
          - /api/v1/auth/logout
        methods:
          - GET
          - POST
        strip_path: false
        preserve_host: true
    plugins:
      - name: cors
        config:
          origins:
            - "http://localhost:3000"
            - "https://localhost:3000"
            - "http://127.0.0.1:3000"
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
            - HEAD
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-Type
            - Authorization
            - X-Requested-With
            - X-CSRF-Token
          exposed_headers:
            - X-Auth-Token
            - Authorization
          credentials: true
          max_age: 3600
          preflight_continue: false
      - name: rate-limiting
        config:
          minute: 30
          hour: 200
          policy: local
          hide_client_headers: false

  # Ticket Service - Protected endpoints
  - name: ticket-service
    url: http://ticket-service:8002
    connect_timeout: 10000
    write_timeout: 10000
    read_timeout: 10000
    retries: 3
    routes:
      - name: ticket-routes
        paths:
          - /api/v1/tickets
        strip_path: false
        preserve_host: true
    plugins:
      - name: cors
        config:
          origins:
            - "http://localhost:3000"
            - "https://localhost:3000"
            - "http://127.0.0.1:3000"
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-Type
            - Authorization
            - X-Requested-With
          credentials: true
          max_age: 3600
      - name: key-auth
        config:
          key_names:
            - Authorization
          hide_credentials: true
      - name: rate-limiting
        config:
          minute: 60
          hour: 1000
          policy: local
          hide_client_headers: false
      - name: request-size-limiting
        config:
          allowed_payload_size: 10

  # Client Service - Protected endpoints
  - name: client-service
    url: http://client-service:8003
    connect_timeout: 10000
    write_timeout: 10000
    read_timeout: 10000
    retries: 3
    routes:
      - name: client-routes
        paths:
          - /api/v1/clients
        strip_path: false
        preserve_host: true
    plugins:
      - name: cors
        config:
          origins:
            - "http://localhost:3000"
            - "https://localhost:3000"
            - "http://127.0.0.1:3000"
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-Type
            - Authorization
            - X-Requested-With
          credentials: true
          max_age: 3600
      - name: key-auth
        config:
          key_names:
            - Authorization
          hide_credentials: true
      - name: rate-limiting
        config:
          minute: 60
          hour: 1000
          policy: local
      - name: request-size-limiting
        config:
          allowed_payload_size: 5

  # Notification Service - Protected endpoints
  - name: notification-service
    url: http://notification-service:8004
    connect_timeout: 10000
    write_timeout: 10000
    read_timeout: 10000
    retries: 3
    routes:
      - name: notification-routes
        paths:
          - /api/v1/notifications
        strip_path: false
        preserve_host: true
    plugins:
      - name: cors
        config:
          origins:
            - "http://localhost:3000"
            - "https://localhost:3000"
            - "http://127.0.0.1:3000"
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-Type
            - Authorization
            - X-Requested-With
          credentials: true
          max_age: 3600
      - name: key-auth
        config:
          key_names:
            - Authorization
          hide_credentials: true
      - name: rate-limiting
        config:
          minute: 100
          hour: 2000
          policy: local

  # Email Service - Protected endpoints
  - name: email-service
    url: http://email-service:8005
    connect_timeout: 10000
    write_timeout: 30000  # Longer timeout for email processing
    read_timeout: 30000
    retries: 3
    routes:
      - name: email-management-routes
        paths:
          - /api/v1/emails
          - /api/v1/accounts  # Email accounts
          - /api/v1/templates  # Email templates
        strip_path: false
        preserve_host: true
    plugins:
      - name: cors
        config:
          origins:
            - "http://localhost:3000"
            - "https://localhost:3000"
            - "http://127.0.0.1:3000"
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
            - HEAD
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-Type
            - Authorization
            - X-Requested-With
            - X-CSRF-Token
          exposed_headers:
            - X-Total-Count
            - X-Page-Count
          credentials: true
          max_age: 3600
      - name: key-auth
        config:
          key_names:
            - Authorization
          hide_credentials: true
      - name: rate-limiting
        config:
          minute: 50  # Higher limit for email operations
          hour: 800
          policy: local
          hide_client_headers: false
      - name: request-size-limiting
        config:
          allowed_payload_size: 25  # 25MB for email attachments

  # AI Integration Service - Protected endpoints
  - name: ai-integration-service
    url: http://ai-integration-service:8006
    connect_timeout: 15000
    write_timeout: 60000  # Longer timeout for AI processing
    read_timeout: 60000
    retries: 2
    routes:
      - name: ai-process-routes
        paths:
          - /api/v1/process
          - /api/v1/configurations
          - /api/v1/providers
          - /api/v1/monitoring
          - /api/v1/features
          - /api/v1/queue
        strip_path: false
        preserve_host: true
      - name: ai-webhook-routes
        paths:
          - /api/v1/webhooks
        strip_path: false
        preserve_host: true
    plugins:
      - name: cors
        config:
          origins:
            - "http://localhost:3000"
            - "https://localhost:3000"
            - "http://127.0.0.1:3000"
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
            - HEAD
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-Type
            - Authorization
            - X-Requested-With
            - X-CSRF-Token
          exposed_headers:
            - X-Request-ID
          credentials: true
          max_age: 3600
      - name: rate-limiting
        config:
          minute: 30  # Lower limit for AI operations
          hour: 500
          policy: local
          hide_client_headers: false
      - name: request-size-limiting
        config:
          allowed_payload_size: 5

  # Health Check Service - Public endpoint
  - name: health-service
    url: http://localhost:8000
    routes:
      - name: health-routes
        paths:
          - /health
          - /api/v1/health
        methods:
          - GET
        strip_path: false

# Global Plugins
plugins:
  # Monitoring and Metrics
  - name: prometheus
    config:
      per_consumer: false
      status_code_metrics: true
      latency_metrics: true
      bandwidth_metrics: true
      upstream_health_metrics: true

  # Request/Response Logging
  - name: file-log
    config:
      path: /tmp/access.log
      reopen: true

  # Request Transformation
  - name: request-transformer
    config:
      add:
        headers:
          - "X-Forwarded-Prefix:/api/v1"
          - "X-Gateway:Kong"
          - "X-Request-ID:$request_id"

  # Security Headers
  - name: response-transformer
    config:
      add:
        headers:
          - "X-Frame-Options:DENY"
          - "X-Content-Type-Options:nosniff"
          - "X-XSS-Protection:1; mode=block"
          - "Referrer-Policy:strict-origin-when-cross-origin"
          - "Content-Security-Policy:default-src 'self'"

  # IP Restriction for Admin routes (optional)
  - name: ip-restriction
    config:
      allow:
        - 127.0.0.1
        - 172.16.0.0/12
        - 192.168.0.0/16
        - 10.0.0.0/8