<?php

namespace App\Services;

use Illuminate\Support\Facades\Log;

class EmailService
{
    /**
     * Send email (simplified implementation)
     * In production, this would integrate with your email service (SendGrid, SES, etc.)
     */
    public function sendEmail(string $recipient, string $subject, string $body, array $attachments = []): bool
    {
        try {
            // For now, just log the email (in production, you'd send actual emails)
            Log::info("Sending email", [
                'recipient' => $recipient,
                'subject' => $subject,
                'attachments' => count($attachments)
            ]);

            // In production, you would implement actual email sending here:
            // - Use Laravel's Mail facade with configured driver
            // - Or use direct API calls to email service providers
            // - Handle attachments, HTML formatting, etc.

            // Simulate email sending delay
            usleep(100000); // 100ms

            return true;

        } catch (\Exception $e) {
            Log::error("Failed to send email", [
                'recipient' => $recipient,
                'subject' => $subject,
                'error' => $e->getMessage()
            ]);

            return false;
        }
    }

    /**
     * Send multiple emails (batch)
     */
    public function sendBatchEmails(array $emails): array
    {
        $results = [];

        foreach ($emails as $email) {
            $recipient = $email['recipient'] ?? '';
            $subject = $email['subject'] ?? '';
            $body = $email['body'] ?? '';
            $attachments = $email['attachments'] ?? [];

            $results[$recipient] = $this->sendEmail($recipient, $subject, $body, $attachments);
        }

        return $results;
    }

    /**
     * Validate email address
     */
    public function validateEmail(string $email): bool
    {
        return filter_var($email, FILTER_VALIDATE_EMAIL) !== false;
    }

    /**
     * Build HTML email template
     */
    public function buildHtmlTemplate(string $title, string $content, array $data = []): string
    {
        return "
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <title>{$title}</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        .container {
            max-width: 600px;
            margin: 20px auto;
            background-color: white;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        .header {
            background-color: #3b82f6;
            color: white;
            padding: 30px 20px;
            text-align: center;
        }
        .content {
            padding: 30px 20px;
        }
        .footer {
            background-color: #f8f9fa;
            color: #6c757d;
            padding: 20px;
            text-align: center;
            font-size: 14px;
        }
        .metrics-table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        .metrics-table th,
        .metrics-table td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        .metrics-table th {
            background-color: #f8f9fa;
            font-weight: 600;
        }
        .button {
            display: inline-block;
            padding: 12px 24px;
            background-color: #3b82f6;
            color: white;
            text-decoration: none;
            border-radius: 6px;
            margin: 10px 0;
        }
    </style>
</head>
<body>
    <div class='container'>
        <div class='header'>
            <h1>{$title}</h1>
            <p>AidlY Analytics Report</p>
        </div>
        <div class='content'>
            {$content}
        </div>
        <div class='footer'>
            <p>Generated by AidlY Analytics Service</p>
            <p>This is an automated message. Please do not reply to this email.</p>
        </div>
    </div>
</body>
</html>";
    }
}